name: Build Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Test against different Node.js versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js environment for JavaScript/TypeScript tests
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Install Node.js dependencies
    - name: Install dependencies
      run: npm install

    # Run the JavaScript unit tests
    - name: Run Node.js Tests
      run: npm test