name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] # Test against different Node.js versions

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm test

    # Setup Java for Android unit tests
    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # Or 'zulu'
        java-version: ${{ matrix.java-version }}

    # Run the Android unit tests with gradlew
    - name: Run Android Unit Tests
      run: ./gradlew test --no-daemon
